researcher_task:
  description: >
    Conduct a thorough research about {topic}
    Make sure you find any interesting and relevant information given
    the current year is {year} in {month}. 1. Prioritize the latest trends, 
    key players, and noteworthy news on {topic}. 2. Identify the target 
    audience, considering their interests and pain points. 3. Develop a 
    detailed content outline including an introduction, key points, and a 
    call to action. 4. Include SEO keywords and relevant data or sources.
  expected_output: >
    A list with 10 bullet points of the most relevant information about {topic}
    with A comprehensive content, an outline, audience analysis, SEO keywords, 
    and resources.
  agent: researcher
  output_file: report.md
