writer_task:
  description: >
    1. Use the content plan to craft a compelling message on {topic}.
    2. Ensure the message is structured with an engaging insightful information, clear and concise.
    3. Use emojis to make it more engaging.
    4. Proofread for grammatical errors and alignment with the brand's voice which is friendly vibe, clear info, and a dash of fun.
    5. At the end of the message, include a section for external links using the provided URLs, these are ({tweetLink}, {linkedinLink} and {notionLink}).
    6. Write a short message that resonates with {topic} enthusiasts.
  
  expected_output: >
    A well-written message in markdown format, ready for publication, each 
    section should have 1 or 2 paragraphs of 3 lines max (each line of 6 words approx).
  agent: writer

editor_task:
  description: >
    Proofread the given message for grammatical errors and alignment with 
    the brand's voice which is friendly vibe, clear info, and a dash of fun.
  expected_output: >
    A well-written message, ready for publication, each 
    section should have 1 or 2 paragraphs of 3 lines max (each line of 6 words approx).
  agent: editor