# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure Functions: https://aka.ms/python-webapps-actions

name: Build and deploy Python project to Azure Function App - postautomation

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'
  PYTHON_VERSION: '3.11'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python version
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Clean Python Cache
        run: |
          find . -type d -name "__pycache__" -exec rm -r {} +
          rm -rf .pytest_cache

      - name: Create deployment package
        run: |
          zip -r release.zip . -i '*.py' '*.json' '*.txt' 'host.json' 'requirements.txt'  # Estructura corregida

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    permissions:
      id-token: write

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip package
        run: unzip release.zip -d deployment_package

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v2  # Versión actualizada
        id: deploy-to-function
        with:
          app-name: 'postautomation'
          slot-name: 'Production'
          package: 'deployment_package'
          enable-oryx-build: true  # Build específico para Python
          runtime: 'python'  # Runtime explícito
          runtime-version: '3.11'  # Versión específica
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}

      - name: Verify deployment
        run: |
          az functionapp config appsettings list \
          --name postautomation \
          --resource-group YOUR_RESOURCE_GROUP_NAME \
          --query "[?name=='WEBSITE_RUN_FROM_PACKAGE'].value"
